/**
 * CANONICAL REASONING CONTRACT
 * =============================
 *
 * This is the single runtime boundary between untrusted LLM output and
 * SignalGOAT business logic.
 *
 * Pipeline:
 *
 *   LLM JSON
 *      ↓
 *   parseReasoningResult()
 *      ↓
 *   validated ReasoningResult
 *      ↓
 *   GoatDurableObject
 *      ↓
 *   SignalGate
 *
 * IMPORTANT:
 * - Never pass raw LLM JSON into business logic.
 * - Never trust model-calculated risk/reward.
 * - Never trust model output as market-data truth.
 * - Deterministic runtime validation remains authoritative.
 *
 * Concept separation:
 *   direction  = LONG | SHORT
 *   orderType  = LIMIT | STOP | MARKET
 *   bias       = BULLISH | BEARISH | NEUTRAL
 *   decision   = ACTIONABLE | NO_TRADE
 */

import {
  TradeDirection,
  OrderType,
  MarketBias,
  ReasoningDecision,
  TrackerCondition,
  TrackerConditionType,
  TrackerOperator,
  TrackerIndicatorParams,
  IndicatorType,
  INDICATOR_TYPES,
  TRACKER_CONDITION_TYPES as TYPE_TRACKER_CONDITION_TYPES,
  TRACKER_OPERATORS as TYPE_TRACKER_OPERATORS,
} from '../../types';

export type {
  TradeDirection,
  OrderType,
  MarketBias,
  ReasoningDecision,
  TrackerConditionType,
  TrackerOperator,
  IndicatorType,
};

/* ------------------------------------------------------------------ */
/* Canonical enums                                                    */
/* ------------------------------------------------------------------ */

export type EvidenceClassification =
  | 'SUPPORTING'
  | 'CONTRADICTORY';

export const TRACKER_CONDITION_TYPES =
  TYPE_TRACKER_CONDITION_TYPES;

export const TRACKER_OPERATORS =
  TYPE_TRACKER_OPERATORS;

export const INDICATOR_TYPES_LIST =
  INDICATOR_TYPES;

const SESSION_TYPES = [
  'LONDON',
  'NEW_YORK',
  'ASIAN',
] as const;

const MARKET_BIASES = [
  'BULLISH',
  'BEARISH',
  'NEUTRAL',
] as const;

const TRADE_DIRECTIONS = [
  'LONG',
  'SHORT',
] as const;

const ORDER_TYPES = [
  'LIMIT',
  'STOP',
  'MARKET',
] as const;

const REASONING_DECISIONS = [
  'ACTIONABLE',
  'NO_TRADE',
] as const;

const EVIDENCE_CLASSIFICATIONS = [
  'SUPPORTING',
  'CONTRADICTORY',
] as const;

/* ------------------------------------------------------------------ */
/* Canonical reasoning shapes                                         */
/* ------------------------------------------------------------------ */

export interface EvidenceItem {
  /**
   * Stable identifier generated by the parser.
   *
   * The model does not control this value.
   */
  id: string;

  /**
   * What produced the observation.
   *
   * Examples:
   *   RSI_14
   *   EMA_CROSS
   *   STRUCTURE
   *   LLM_PATTERN
   */
  source: string;

  market: string;

  timeframe?: string;

  /**
   * Human-readable observation.
   *
   * This is an interpretation supplied by the model and must not be
   * treated as independently verified market data.
   */
  observation: string;

  bias?: MarketBias;

  classification: EvidenceClassification;

  /**
   * Optional model timestamp.
   *
   * Runtime timestamps remain authoritative elsewhere.
   */
  timestamp?: number;
}

export interface TrackerDirective {
  description: string;
  type: TrackerConditionType;

  /**
   * Indicator expression.
   *
   * A tracker is "an indicator being in a certain value" — e.g.
   *   { indicator: 'EMA', period: 20 } CROSS_ABOVE targetValue: 1.2345
   *   { indicator: 'RSI', period: 14 } CROSS_BELOW targetValue: 30
   *
   * The runtime recomputes the value from candles and compares it to
   * targetValue. A tracker with an indicator and a targetValue is therefore
   * fully deterministic and never depends on the model at evaluation time.
   */
  indicator?: IndicatorType;
  period?: number;
  fastPeriod?: number;
  slowPeriod?: number;
  session?: 'LONDON' | 'NEW_YORK' | 'ASIAN';

  targetValue?: number;
  operator?: TrackerOperator;
}

export interface ReasoningInvestigation {
  summary: string;
  marketView?: string;
}

export interface ReasoningThesis {
  directionalBias: MarketBias;
  summary: string;
  confidence: number;
  invalidation?: string;
  observationPlan?: string;
  trackers: TrackerDirective[];
}

export interface TradeProposal {
  decision: ReasoningDecision;

  direction?: TradeDirection;
  orderType?: OrderType;

  /**
   * Optional because the runtime already knows which market is being
   * evaluated. If supplied by the model, SignalGate must verify it.
   */
  market?: string;

  entry?: number;

  entryZone?: {
    low: number;
    high: number;
  } | null;

  stopLoss?: number;
  takeProfit?: number;

  /**
   * THE CONDITIONAL TRADE IDEA.
   *
   * An ordered chain of wait-for conditions, e.g.
   *   1. "EMA(20) crosses above 1.2345"
   *   2. "price holds above 1.2340 for one 1h close"
   *   3. "then consider LONG from the 1.2340-1.2360 zone"
   *
   * A signal is NEVER "buy now". Every actionable proposal must describe the
   * conditions that must be satisfied FIRST. Each entry is additionally
   * materialised as a deterministic Tracker so the platform can alert the
   * user when a condition is actually met.
   */
  triggerSequence?: string[];

  /**
   * Model-calculated RR is informational only.
   *
   * SignalGate must calculate authoritative RR from entry/SL/TP.
   */
  riskReward?: number;

  /**
   * Proposal confidence is informational. Thesis confidence is the
   * canonical confidence used by the current runtime gate.
   */
  confidence?: number;

  rationale?: string;
  confirmationRequired?: string;
  invalidation?: string;
  noTradeReason?: string;
}

export interface ReasoningResult {
  investigation: ReasoningInvestigation;
  thesis: ReasoningThesis;
  proposal: TradeProposal;
  evidence: EvidenceItem[];
}

/* ------------------------------------------------------------------ */
/* Validation error                                                   */
/* ------------------------------------------------------------------ */

export class ReasoningValidationError extends Error {
  readonly issues: string[];

  constructor(issues: string[]) {
    super(
      `Reasoning result failed validation: ${issues.join('; ')}`,
    );

    this.name = 'ReasoningValidationError';
    this.issues = issues;
  }
}

/* ------------------------------------------------------------------ */
/* Limits                                                             */
/* ------------------------------------------------------------------ */

const MAX_STRING_LENGTHS = {
  summary: 2000,
  observation: 1000,
  rationale: 2000,
  source: 64,
  description: 500,
  market: 32,
  timeframe: 16,
  invalidation: 1000,
  confirmation: 500,
  noTradeReason: 2000,
} as const;

const MAX_EVIDENCE_ITEMS = 30;
const MAX_TRACKERS = 10;

/** Upper bound on the "wait for this, then that" chain of a proposal. */
const MAX_TRIGGER_SEQUENCE_STEPS = 6;

/* ------------------------------------------------------------------ */
/* Generic validation helpers                                         */
/* ------------------------------------------------------------------ */

function isPlainObject(
  value: unknown,
): value is Record<string, unknown> {
  return (
    typeof value === 'object' &&
    value !== null &&
    !Array.isArray(value)
  );
}

/**
 * Parses an optional array-of-strings field, dropping non-string and
 * over-long entries rather than failing the whole response.
 */
function parseStringArrayField(
  value: unknown,
  label: string,
  issues: string[],
  maxItems: number,
  maxLength: number,
): string[] {
  if (value === undefined || value === null) {
    return [];
  }

  if (!Array.isArray(value)) {
    issues.push(
      `${label} must be an array of strings`,
    );
    return [];
  }

  if (value.length > maxItems) {
    issues.push(
      `${label} must contain at most ${maxItems} items`,
    );
    return [];
  }

  const out: string[] = [];

  for (const item of value) {
    if (typeof item !== 'string') {
      issues.push(
        `${label} must contain only strings`,
      );
      return [];
    }

    const trimmed = item.trim();

    if (!trimmed) {
      issues.push(
        `${label} must not contain empty strings`,
      );
      return [];
    }

    out.push(
      trimmed.slice(0, maxLength),
    );
  }

  return out;
}

/**
 * Parses a finite numeric value.
 *
 * Numeric strings are accepted because LLMs frequently emit numbers
 * as strings despite being instructed to emit JSON numbers.
 *
 * NaN, Infinity, empty strings and arbitrary values are rejected.
 */
function parseFiniteNumber(
  value: unknown,
  label: string,
  issues: string[],
): number | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }

  if (
    typeof value === 'number' &&
    Number.isFinite(value)
  ) {
    return value;
  }

  if (
    typeof value === 'string' &&
    value.trim() !== ''
  ) {
    const parsed = Number(value);

    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }

  issues.push(`${label} must be a finite number`);

  return undefined;
}

/**
 * Parses a bounded string.
 *
 * We intentionally trim and cap model-generated text rather than
 * allowing an unexpectedly large response to propagate through the
 * runtime/UI.
 */
function parseString(
  value: unknown,
  label: string,
  issues: string[],
  maxLength: number = MAX_STRING_LENGTHS.summary,
  required: boolean = false,
): string | undefined {
  if (value === undefined || value === null) {
    if (required) {
      issues.push(`${label} is required`);
    }

    return undefined;
  }

  if (typeof value !== 'string') {
    issues.push(`${label} must be a string`);
    return undefined;
  }

  const trimmed = value.trim();

  if (required && trimmed.length === 0) {
    issues.push(`${label} must not be empty`);
    return undefined;
  }

  return trimmed.slice(0, maxLength);
}

function parseEnum<T extends string>(
  value: unknown,
  allowed: readonly T[],
  label: string,
  issues: string[],
  required: boolean = false,
): T | undefined {
  if (value === undefined || value === null) {
    if (required) {
      issues.push(`${label} is required`);
    }

    return undefined;
  }

  if (
    typeof value !== 'string' ||
    !allowed.includes(value as T)
  ) {
    issues.push(
      `${label} must be one of: ${allowed.join(', ')}`,
    );

    return undefined;
  }

  return value as T;
}

function validateOptionalNonNegativeNumber(
  value: number | undefined,
  label: string,
  issues: string[],
): void {
  if (
    value !== undefined &&
    value < 0
  ) {
    issues.push(`${label} must be >= 0`);
  }
}

/* ------------------------------------------------------------------ */
/* Evidence                                                           */
/* ------------------------------------------------------------------ */

function parseEvidenceItem(
  raw: unknown,
  index: number,
  defaultMarket: string,
  issues: string[],
): EvidenceItem | undefined {
  const label = `evidence[${index}]`;

  if (!isPlainObject(raw)) {
    issues.push(`${label} must be an object`);
    return undefined;
  }

  const itemIssues: string[] = [];

  const source = parseString(
    raw.source,
    `${label}.source`,
    itemIssues,
    MAX_STRING_LENGTHS.source,
    true,
  );

  const observation = parseString(
    raw.observation,
    `${label}.observation`,
    itemIssues,
    MAX_STRING_LENGTHS.observation,
    true,
  );

  const market =
    parseString(
      raw.market,
      `${label}.market`,
      itemIssues,
      MAX_STRING_LENGTHS.market,
    ) || defaultMarket;

  const timeframe = parseString(
    raw.timeframe,
    `${label}.timeframe`,
    itemIssues,
    MAX_STRING_LENGTHS.timeframe,
  );

  const bias = parseEnum(
    raw.bias,
    MARKET_BIASES,
    `${label}.bias`,
    itemIssues,
  );

  const classification = parseEnum(
    raw.classification,
    EVIDENCE_CLASSIFICATIONS,
    `${label}.classification`,
    itemIssues,
    true,
  );

  const timestamp = parseFiniteNumber(
    raw.timestamp,
    `${label}.timestamp`,
    itemIssues,
  );

  if (timestamp !== undefined && timestamp < 0) {
    itemIssues.push(
      `${label}.timestamp must be >= 0`,
    );
  }

  if (itemIssues.length > 0) {
    issues.push(...itemIssues);
    return undefined;
  }

  /**
   * Stable within this reasoning result.
   *
   * Index is included so identical observations are still represented
   * as distinct evidence items.
   */
  const stableId =
    `ev_${index}_${Math.abs(
      hashString(`${source}|${observation}`),
    ).toString(36)}`;

  return {
    id: stableId,
    source: source!,
    market,
    timeframe,
    observation: observation!,
    bias,
    classification: classification!,
    timestamp:
      timestamp !== undefined
        ? timestamp
        : Date.now(),
  };
}

function parseEvidenceList(
  raw: unknown,
  defaultMarket: string,
  issues: string[],
): EvidenceItem[] {
  if (raw === undefined || raw === null) {
    return [];
  }

  if (!Array.isArray(raw)) {
    issues.push('evidence must be an array');
    return [];
  }

  if (raw.length > MAX_EVIDENCE_ITEMS) {
    issues.push(
      `evidence must contain at most ${MAX_EVIDENCE_ITEMS} items`,
    );
  }

  const items: EvidenceItem[] = [];

  raw
    .slice(0, MAX_EVIDENCE_ITEMS)
    .forEach((entry, index) => {
      const item = parseEvidenceItem(
        entry,
        index,
        defaultMarket,
        issues,
      );

      if (item) {
        items.push(item);
      }
    });

  return items;
}

/* ------------------------------------------------------------------ */
/* Trackers                                                           */
/* ------------------------------------------------------------------ */

function parseTrackerDirective(
  raw: unknown,
  index: number,
  issues: string[],
): TrackerDirective | undefined {
  const label =
    `thesis.trackers[${index}]`;

  if (!isPlainObject(raw)) {
    issues.push(`${label} must be an object`);
    return undefined;
  }

  const itemIssues: string[] = [];

  const description = parseString(
    raw.description,
    `${label}.description`,
    itemIssues,
    MAX_STRING_LENGTHS.description,
    true,
  );

  const type = parseEnum(
    raw.type,
    TRACKER_CONDITION_TYPES,
    `${label}.type`,
    itemIssues,
    true,
  );

  const operator = parseEnum(
    raw.operator,
    TRACKER_OPERATORS,
    `${label}.operator`,
    itemIssues,
  );

  const targetValue = parseFiniteNumber(
    raw.targetValue,
    `${label}.targetValue`,
    itemIssues,
  );

  if (
    targetValue !== undefined &&
    !Number.isFinite(targetValue)
  ) {
    itemIssues.push(
      `${label}.targetValue must be finite`,
    );
  }

  /**
   * Indicator expression parts. These make the tracker deterministically
   * re-computable: "EMA(20) is in this value" instead of an unfalsifiable
   * prose condition.
   */
  const indicator = parseEnum(
    raw.indicator,
    INDICATOR_TYPES,
    `${label}.indicator`,
    itemIssues,
  );

  const period = parseFiniteNumber(
    raw.period,
    `${label}.period`,
    itemIssues,
  );

  const fastPeriod = parseFiniteNumber(
    raw.fastPeriod,
    `${label}.fastPeriod`,
    itemIssues,
  );

  const slowPeriod = parseFiniteNumber(
    raw.slowPeriod,
    `${label}.slowPeriod`,
    itemIssues,
  );

  const session = parseEnum(
    raw.session,
    SESSION_TYPES,
    `${label}.session`,
    itemIssues,
  );

  if (period !== undefined && (period < 1 || period > 500)) {
    itemIssues.push(
      `${label}.period must be between 1 and 500`,
    );
  }

  /**
   * A generic INDICATOR tracker without a target value can never fire, so it
   * is rejected rather than silently armed as dead weight.
   */
  if (
    indicator &&
    targetValue === undefined
  ) {
    itemIssues.push(
      `${label} uses indicator "${indicator}" and must therefore supply a numeric targetValue`,
    );
  }

  if (itemIssues.length > 0) {
    issues.push(...itemIssues);
    return undefined;
  }

  return {
    description: description!,
    type: type!,
    indicator,
    period: period ?? undefined,
    fastPeriod: fastPeriod ?? undefined,
    slowPeriod: slowPeriod ?? undefined,
    session: session ?? undefined,
    targetValue,
    operator,
  };
}

function parseTrackerDirectives(
  raw: unknown,
  issues: string[],
): TrackerDirective[] {
  if (raw === undefined || raw === null) {
    return [];
  }

  if (!Array.isArray(raw)) {
    issues.push(
      'thesis.trackers must be an array',
    );

    return [];
  }

  if (raw.length > MAX_TRACKERS) {
    issues.push(
      `thesis.trackers must contain at most ${MAX_TRACKERS} items`,
    );
  }

  const directives: TrackerDirective[] = [];

  raw
    .slice(0, MAX_TRACKERS)
    .forEach((entry, index) => {
      const directive =
        parseTrackerDirective(
          entry,
          index,
          issues,
        );

      if (directive) {
        directives.push(directive);
      }
    });

  return directives;
}

/* ------------------------------------------------------------------ */
/* Entry zone                                                         */
/* ------------------------------------------------------------------ */

function parseEntryZone(
  raw: unknown,
  issues: string[],
): { low: number; high: number } | null {
  if (raw === undefined || raw === null) {
    return null;
  }

  if (!isPlainObject(raw)) {
    issues.push(
      'proposal.entryZone must be an object or null',
    );

    return null;
  }

  const low = parseFiniteNumber(
    raw.low,
    'proposal.entryZone.low',
    issues,
  );

  const high = parseFiniteNumber(
    raw.high,
    'proposal.entryZone.high',
    issues,
  );

  if (
    low === undefined ||
    high === undefined
  ) {
    return null;
  }

  if (low > high) {
    issues.push(
      'proposal.entryZone.low must be <= proposal.entryZone.high',
    );

    return null;
  }

  return {
    low,
    high,
  };
}

/* ------------------------------------------------------------------ */
/* Proposal                                                           */
/* ------------------------------------------------------------------ */

function parseProposal(
  raw: unknown,
  issues: string[],
): TradeProposal | undefined {
  if (!isPlainObject(raw)) {
    issues.push('proposal must be an object');
    return undefined;
  }

  const itemIssues: string[] = [];

  const decision = parseEnum(
    raw.decision,
    REASONING_DECISIONS,
    'proposal.decision',
    itemIssues,
    true,
  );

  const market = parseString(
    raw.market,
    'proposal.market',
    itemIssues,
    MAX_STRING_LENGTHS.market,
  );

  const direction = parseEnum(
    raw.direction,
    TRADE_DIRECTIONS,
    'proposal.direction',
    itemIssues,
  );

  const orderType = parseEnum(
    raw.orderType,
    ORDER_TYPES,
    'proposal.orderType',
    itemIssues,
  );

  const entry = parseFiniteNumber(
    raw.entry,
    'proposal.entry',
    itemIssues,
  );

  const stopLoss = parseFiniteNumber(
    raw.stopLoss,
    'proposal.stopLoss',
    itemIssues,
  );

  const takeProfit = parseFiniteNumber(
    raw.takeProfit,
    'proposal.takeProfit',
    itemIssues,
  );

  const riskReward = parseFiniteNumber(
    raw.riskReward,
    'proposal.riskReward',
    itemIssues,
  );

  const confidence = parseFiniteNumber(
    raw.confidence,
    'proposal.confidence',
    itemIssues,
  );

  const rationale = parseString(
    raw.rationale,
    'proposal.rationale',
    itemIssues,
    MAX_STRING_LENGTHS.rationale,
  );

  const invalidation = parseString(
    raw.invalidation,
    'proposal.invalidation',
    itemIssues,
    MAX_STRING_LENGTHS.invalidation,
  );

  const confirmationRequired = parseString(
    raw.confirmationRequired,
    'proposal.confirmationRequired',
    itemIssues,
    MAX_STRING_LENGTHS.confirmation,
  );

  const noTradeReason = parseString(
    raw.noTradeReason,
    'proposal.noTradeReason',
    itemIssues,
    MAX_STRING_LENGTHS.noTradeReason,
  );

  const entryZone = parseEntryZone(
    raw.entryZone,
    itemIssues,
  );

  /**
   * The conditional "wait for this, then that, then consider entry" chain.
   */
  const triggerSequence = parseStringArrayField(
    raw.triggerSequence,
    'proposal.triggerSequence',
    itemIssues,
    MAX_TRIGGER_SEQUENCE_STEPS,
    MAX_STRING_LENGTHS.summary,
  );

  /* Numeric sanity checks. */

  validateOptionalNonNegativeNumber(
    riskReward,
    'proposal.riskReward',
    itemIssues,
  );

  if (
    confidence !== undefined &&
    (
      confidence < 0 ||
      confidence > 100
    )
  ) {
    itemIssues.push(
      'proposal.confidence must be between 0 and 100',
    );
  }

  /* Actionability rules. */

  if (decision === 'ACTIONABLE') {
    /**
     * An actionable proposal MUST be conditional. "Buy now" is rejected
     * outright: the platform only ever publishes wait-for setups.
     */
    if (
      triggerSequence.length === 0
    ) {
      itemIssues.push(
        'proposal.triggerSequence is required for an ACTIONABLE proposal — a trade idea must state the conditions to wait for, never "enter now"',
      );
    }

    if (!direction) {
      itemIssues.push(
        'proposal.direction (LONG | SHORT) is required for an ACTIONABLE proposal',
      );
    }

    if (!orderType) {
      itemIssues.push(
        'proposal.orderType (LIMIT | STOP | MARKET) is required for an ACTIONABLE proposal',
      );
    }

    if (entry === undefined) {
      itemIssues.push(
        'proposal.entry is required for an ACTIONABLE proposal',
      );
    }

    if (stopLoss === undefined) {
      itemIssues.push(
        'proposal.stopLoss is required for an ACTIONABLE proposal',
      );
    }

    if (takeProfit === undefined) {
      itemIssues.push(
        'proposal.takeProfit is required for an ACTIONABLE proposal',
      );
    }

    if (
      !rationale ||
      rationale.length === 0
    ) {
      itemIssues.push(
        'proposal.rationale is required for an ACTIONABLE proposal',
      );
    }

    if (
      !invalidation ||
      invalidation.length < 5
    ) {
      itemIssues.push(
        'proposal.invalidation is required (concrete level or rule) for an ACTIONABLE proposal',
      );
    }

    /*
     * A valid trade cannot contain non-positive prices.
     *
     * Instrument-specific validation such as decimal precision,
     * pip size, spread and relationship to bid/ask belongs in
     * SignalGate because this parser does not have market metadata.
     */
    if (
      entry !== undefined &&
      entry <= 0
    ) {
      itemIssues.push(
        'proposal.entry must be greater than 0',
      );
    }

    if (
      stopLoss !== undefined &&
      stopLoss <= 0
    ) {
      itemIssues.push(
        'proposal.stopLoss must be greater than 0',
      );
    }

    if (
      takeProfit !== undefined &&
      takeProfit <= 0
    ) {
      itemIssues.push(
        'proposal.takeProfit must be greater than 0',
      );
    }

    if (
      entryZone &&
      entry !== undefined &&
      (
        entry < entryZone.low ||
        entry > entryZone.high
      )
    ) {
      itemIssues.push(
        'proposal.entry must fall within proposal.entryZone',
      );
    }
  } else if (decision === 'NO_TRADE') {
    if (
      !noTradeReason ||
      noTradeReason.length === 0
    ) {
      itemIssues.push(
        'proposal.noTradeReason is required for a NO_TRADE proposal',
      );
    }
  }

  if (itemIssues.length > 0) {
    issues.push(...itemIssues);
    return undefined;
  }

  return {
    decision: decision!,
    market,
    direction,
    orderType,
    entry,
    entryZone,
    stopLoss,
    takeProfit,
    triggerSequence,
    riskReward,
    confidence,
    rationale,
    confirmationRequired,
    invalidation,
    noTradeReason,
  };
}

/* ------------------------------------------------------------------ */
/* Investigation                                                      */
/* ------------------------------------------------------------------ */

function parseInvestigation(
  raw: unknown,
  issues: string[],
): ReasoningInvestigation | undefined {
  if (!isPlainObject(raw)) {
    issues.push(
      'investigation must be an object',
    );

    return undefined;
  }

  const itemIssues: string[] = [];

  const summary = parseString(
    raw.summary,
    'investigation.summary',
    itemIssues,
    MAX_STRING_LENGTHS.summary,
    true,
  );

  const marketView = parseString(
    raw.marketView,
    'investigation.marketView',
    itemIssues,
    MAX_STRING_LENGTHS.summary,
  );

  if (itemIssues.length > 0) {
    issues.push(...itemIssues);
    return undefined;
  }

  return {
    summary: summary!,
    marketView,
  };
}

/* ------------------------------------------------------------------ */
/* Thesis                                                             */
/* ------------------------------------------------------------------ */

function parseThesis(
  raw: unknown,
  issues: string[],
): ReasoningThesis | undefined {
  if (!isPlainObject(raw)) {
    issues.push(
      'thesis must be an object',
    );

    return undefined;
  }

  const itemIssues: string[] = [];

  const directionalBias = parseEnum(
    raw.directionalBias,
    MARKET_BIASES,
    'thesis.directionalBias',
    itemIssues,
    true,
  );

  const summary = parseString(
    raw.summary,
    'thesis.summary',
    itemIssues,
    MAX_STRING_LENGTHS.summary,
    true,
  );

  const confidence = parseFiniteNumber(
    raw.confidence,
    'thesis.confidence',
    itemIssues,
  );

  const invalidation = parseString(
    raw.invalidation,
    'thesis.invalidation',
    itemIssues,
    MAX_STRING_LENGTHS.invalidation,
  );

  const observationPlan = parseString(
    raw.observationPlan,
    'thesis.observationPlan',
    itemIssues,
    MAX_STRING_LENGTHS.summary,
  );

  const trackers = parseTrackerDirectives(
    raw.trackers,
    itemIssues,
  );

  if (
    confidence === undefined ||
    confidence < 0 ||
    confidence > 100
  ) {
    itemIssues.push(
      'thesis.confidence must be a number between 0 and 100',
    );
  }

  if (itemIssues.length > 0) {
    issues.push(...itemIssues);
    return undefined;
  }

  return {
    directionalBias: directionalBias!,
    summary: summary!,
    confidence: confidence!,
    invalidation,
    observationPlan,
    trackers,
  };
}

/* ------------------------------------------------------------------ */
/* Top-level parser                                                   */
/* ------------------------------------------------------------------ */

/**
 * The primary security/runtime boundary for model output.
 *
 * UNKNOWN JSON enters here.
 *
 * Only a fully validated ReasoningResult leaves here.
 *
 * Throws:
 *   ReasoningValidationError
 *
 * Never allow raw parsed model JSON to bypass this function.
 */
export function parseReasoningResult(
  raw: unknown,
): ReasoningResult {
  const issues: string[] = [];

  if (!isPlainObject(raw)) {
    throw new ReasoningValidationError([
      'response must be a JSON object',
    ]);
  }

  const investigation =
    parseInvestigation(
      raw.investigation,
      issues,
    );

  /*
   * Proposal market is only a fallback for evidence.
   *
   * The runtime market is authoritative and will be checked later
   * by SignalGate.
   */
  const marketFromProposal =
    isPlainObject(raw.proposal) &&
    typeof raw.proposal.market === 'string'
      ? raw.proposal.market.trim()
      : undefined;

  const evidence =
    parseEvidenceList(
      raw.evidence,
      marketFromProposal || 'unknown',
      issues,
    );

  const thesis =
    parseThesis(
      raw.thesis,
      issues,
    );

  const proposal =
    parseProposal(
      raw.proposal,
      issues,
    );

  if (
    issues.length > 0 ||
    !investigation ||
    !thesis ||
    !proposal
  ) {
    throw new ReasoningValidationError(
      issues.length > 0
        ? issues
        : [
            'response is missing required sections',
          ],
    );
  }

  return {
    investigation,
    thesis,
    proposal,
    evidence,
  };
}

/* ------------------------------------------------------------------ */
/* Shared utilities                                                   */
/* ------------------------------------------------------------------ */

/**
 * Small deterministic string hash.
 *
 * Used only for stable evidence identifiers.
 * It is NOT a cryptographic hash.
 */
export function hashString(
  value: string,
): number {
  let hash = 0;

  for (
    let i = 0;
    i < value.length;
    i++
  ) {
    hash =
      (hash << 5) -
      hash +
      value.charCodeAt(i);

    hash |= 0;
  }

  return hash;
}

/**
 * Deterministic seeded PRNG (mulberry32).
 *
 * Useful for PAPER/backtest simulations where reproducibility matters.
 */
export function seededRandom(
  seed: number,
): () => number {
  let a = seed >>> 0;

  return () => {
    a |= 0;
    a =
      (a + 0x6d2b79f5) |
      0;

    let t =
      Math.imul(
        a ^ (a >>> 15),
        1 | a,
      );

    t =
      (t +
        Math.imul(
          t ^ (t >>> 7),
          61 | t,
        )) ^
      t;

    return (
      ((t ^ (t >>> 14)) >>> 0) /
      4294967296
    );
  };
}

/**
 * Sanitize error messages before they reach UI/API responses.
 */
export function sanitizeErrorMessage(
  message: string,
): string {
  return message
    .replace(
      /sk-or-v1-[a-zA-Z0-9_-]+/g,
      '[REDACTED_API_KEY]',
    )
    .replace(
      /Bearer\s+[^\s]+/gi,
      'Bearer [REDACTED]',
    )
    .replace(
      /bot\d+:[A-Za-z0-9_-]+/g,
      '[REDACTED_BOT_TOKEN]',
    )
    .slice(0, 500);
}